### ISSUE TITLE
We need a 'spinner'

### ISSUE THREAD

**Issue by edcs** [Pod-Point/frontend-framework#14]
Would be cool if we had some form of generic "i'm doing stuff here" progress indicator. I'm not sure what this would look like! Perhaps it could be as simple as adding an icon to a button?

**Comment by InventingWithMonster** [comment]
Progress SVG (use inline): https://github.com/Pod-Point/pod-point.com/blob/master/craft/templates/layout/inline-images/tick-icon.html
